In [1]:
import pandas as pd

In [2]:
# Column names from Freddie Mac documentation
ORIG_COLUMNS = [
    "credit_score", "first_payment_date", "first_time_homebuyer",
    "maturity_date", "msa", "mi_pct", "num_units", "occupancy",
    "cltv", "dti", "original_upb", "ltv", "original_interest_rate",
    "channel", "ppm_flag", "product_type", "property_state",
    "property_type", "postal_code", "loan_sequence_number",
    "loan_purpose", "original_loan_term", "num_borrowers",
    "seller_name", "servicer_name", "super_conforming_flag",
    "pre_harp_loan_seq_num", "program_indicator", "harp_indicator",
    "property_valuation_method", "io_indicator", "mi_cancellation_indicator"
]

In [3]:
df = pd.read_csv(
    "data/sample_2019/sample_orig_2019.txt",
    sep="|",
    header=None,
    names=ORIG_COLUMNS,low_memory=False
)
df.head()

,credit_score,first_payment_date,first_time_homebuyer,maturity_date,msa,mi_pct,num_units,occupancy,cltv,dti,...,num_borrowers,seller_name,servicer_name,super_conforming_flag,pre_harp_loan_seq_num,program_indicator,harp_indicator,property_valuation_method,io_indicator,mi_cancellation_indicator
0,741,201903,N,204902,NaN,0,1,P,80,33,...,2,Other sellers,Other servicers,NaN,NaN,9,NaN,7,N,7
1,731,201903,N,204902,13460.0,0,1,P,77,44,...,1,Other sellers,Other servicers,NaN,NaN,9,NaN,7,N,7
2,722,201903,N,204902,NaN,30,1,P,95,41,...,2,Other sellers,Other servicers,NaN,NaN,9,NaN,7,N,N
3,729,201903,N,204902,NaN,25,1,P,87,17,...,1,Other sellers,Other servicers,NaN,NaN,9,NaN,7,N,N
4,773,201903,N,204902,33700.0,0,1,P,29,43,...,2,Other sellers,Other servicers,NaN,NaN,9,NaN,7,N,7

In [4]:
df.shape

(50000, 32)

In [5]:
df[["credit_score","original_interest_rate", "original_upb", "ltv", "dti", "property_state"]].head(10)

   credit_score  original_interest_rate  original_upb  ltv  dti property_state
0           741                   5.125        372000   80   33             WY
1           731                   4.875        250000   77   44             OR
2           722                   5.500        261000   95   41             IN
3           729                   5.090         61000   87   17             MI
4           773                   5.375        390000   29   43             CA
5           780                   4.750        392000   90   47             CO
6           782                   5.125        316000   80   34             KY
7           772                   4.375        212000   80   29             IL
8           708                   5.125        226000   80   22             OH
9           744                   5.125         86000   57   39             MI

In [13]:
df[["credit_score","original_interest_rate", "original_upb", "ltv", "dti"]].describe()

,credit_score,original_interest_rate,original_upb,ltv,dti
count,50000.00000,50000.000000,5.000000e+04,50000.000000,49969.000000
mean,752.72134,4.237770,2.545748e+05,75.644580,35.314555
std,180.90233,0.586342,1.300801e+05,16.811197,9.372853
min,562.00000,2.350000,1.500000e+04,5.000000,1.000000
25%,719.00000,3.875000,1.550000e+05,69.000000,29.000000
50%,757.00000,4.125000,2.320000e+05,80.000000,37.000000
75%,785.00000,4.625000,3.350000e+05,90.000000,43.000000
max,9999.00000,6.750000,1.397000e+06,103.000000,50.000000

In [17]:
print((df["ltv"] == 999).sum())
print((df["cltv"] == 999).sum())
print((df["mi_pct"] == 999).sum())
print((df["num_borrowers"] == 99).sum())

0
0
0
0

In [18]:
import numpy as np

# Replace sentinel value with NaN (missing)
df["credit_score"]=df["credit_score"].replace(9999,np.nan)
df["dti"]=df["dti"].replace(999,np.nan)
df["cltv"]=df["cltv"].replace(999,np.nan)

In [20]:
df[["credit_score","original_interest_rate", "original_upb", "ltv", "dti","cltv"]].describe()

,credit_score,original_interest_rate,original_upb,ltv,dti,cltv
count,49982.000000,50000.000000,5.000000e+04,50000.000000,49969.000000,49999.000000
mean,749.391481,4.237770,2.545748e+05,75.644580,35.314555,75.815376
std,44.010562,0.586342,1.300801e+05,16.811197,9.372853,16.809688
min,562.000000,2.350000,1.500000e+04,5.000000,1.000000,5.000000
25%,719.000000,3.875000,1.550000e+05,69.000000,29.000000,69.000000
50%,757.000000,4.125000,2.320000e+05,80.000000,37.000000,80.000000
75%,785.000000,4.625000,3.350000e+05,90.000000,43.000000,90.000000
max,832.000000,6.750000,1.397000e+06,103.000000,50.000000,105.000000

In [23]:
# Servicing file column names (From freddi documentation)
SVCG_COLUMNS = [
    "loan_sequence_number", "monthly_reporting_period", "current_actual_upb",
    "current_loan_delinquency_status", "loan_age", "remaining_months_to_maturity",
    "defect_settlement_date", "modification_flag", "zero_balance_code",
    "zero_balance_effective_date", "current_interest_rate", "current_deferred_upb",
    "ddlpi", "mi_recoveries", "net_sales_proceeds", "non_mi_recoveries",
    "total_expenses", "legal_costs", "maintenance_and_preservation_costs",
    "taxes_and_insurance", "miscellaneous_expenses", "actual_loss_calculation",
    "modification_cost", "step_modification_flag", "deferred_payment_plan",
    "estimated_loan_to_value", "zero_balance_removal_upb", "delinquent_accrued_interest",
    "delinquency_due_to_disaster", "borrower_assistance_status_code",
    "current_month_modification_cost", "interest_bearing_upb"
]

svcg=pd.read_csv(
    "data/sample_2019/sample_svcg_2019.txt",
    sep="|",
    header=None,
    names=SVCG_COLUMNS,low_memory=False
)
print(f" Number of rows:{len(svcg):,}")
print(f" Number of columns:{len(svcg.columns)}")

 Number of rows:1,847,477
 Number of columns:32

In [24]:
svcg.head()

,loan_sequence_number,monthly_reporting_period,current_actual_upb,current_loan_delinquency_status,loan_age,remaining_months_to_maturity,defect_settlement_date,modification_flag,zero_balance_code,zero_balance_effective_date,...,modification_cost,step_modification_flag,deferred_payment_plan,estimated_loan_to_value,zero_balance_removal_upb,delinquent_accrued_interest,delinquency_due_to_disaster,borrower_assistance_status_code,current_month_modification_cost,interest_bearing_upb
0,F19Q10000056,201902,372000.0,0,0,360,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,999,NaN,NaN,NaN,NaN,NaN,372000.0
1,F19Q10000056,201903,372000.0,0,1,359,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,999,NaN,NaN,NaN,NaN,NaN,372000.0
2,F19Q10000056,201904,371000.0,0,2,358,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,999,NaN,NaN,NaN,NaN,NaN,371000.0
3,F19Q10000056,201905,370000.0,0,3,357,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,999,NaN,NaN,NaN,NaN,NaN,370000.0
4,F19Q10000056,201906,370000.0,0,4,356,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,75,NaN,NaN,NaN,NaN,NaN,370000.0

In [25]:
svcg["zero_balance_code"].value_counts(dropna=False)

zero_balance_code
NaN     1812215
1.0       35073
96.0        123
16.0         30
2.0          16
9.0          10
15.0          7
3.0           3
Name: count, dtype: int64

In [28]:
prepayments=svcg[svcg["zero_balance_code"]==1.0].copy()
print(f"Number of prepayment events: {len(prepayments):,}")
prepayments[["loan_sequence_number", "monthly_reporting_period", "loan_age", "current_actual_upb"]].head(10)

Number of prepayment events: 35,073

,loan_sequence_number,monthly_reporting_period,loan_age,current_actual_upb
38,F19Q10000056,202204,38,0.0
54,F19Q10000060,202005,15,0.0
69,F19Q10000084,202004,14,0.0
86,F19Q10000106,202006,16,0.0
104,F19Q10000189,202007,17,0.0
110,F19Q10000231,201907,5,0.0
121,F19Q10000239,201912,10,0.0
128,F19Q10000244,201908,6,0.0
140,F19Q10000248,202001,11,0.0
175,F19Q10000268,202112,34,0.0